Run tests/rails from root folder
By doing this it will provide a more direct output to what is
happening in the tests. It also means that you can run the app from
the root folder without having to navigate to the dummy app

* Feature specs run from root
* Single feature spec route
* Do not run rake task twice
* Provide simple Procfile for running rails server
* stub out rails and rspec
* bin/setup is much more simple now
* Upgrade dependencies in gemspec to match what is needed for
  application
* Silence output from puma when running tests

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,14 +1,18 @@
-#!/bin/sh
+#!/usr/bin/env sh
 
-export RAILS_ENV=test
+# Exit if any subcommand fails
+set -e
 
-bundle install
+# Set up Ruby dependencies via Bundler
+gem install bundler --conservative
+bundle check || bundle install
 
-(
-cd spec/dummy && \
-  rm db/migrate/*_create_last_notifications.rb
-  bundle install && \
-  rake db:environment:set db:drop db:create && \
-  rails generate french_toast:install && \
-  rake db:migrate
-)
+# Set up database and add any development seed data
+bundle exec rake db:setup
+
+mkdir -p .git/safe
+
+if ! command -v foreman > /dev/null; then
+  printf "Foreman is not installed.\n"
+  printf "See https://github.com/ddollar/foreman for install instructions.\n"
+fi
